### ISSUE TITLE
Hardware recommendations

### ISSUE THREAD

**Issue by Haimana** [htool/signalk-navtex-plugin#1]
Hello, and congrats for your work

Is it possible to have some more info about the hardware used/tested?
It should work with RSP1A?

Thanks,
Seb

**Comment by htool** [comment]
Hi Haimana,

It currently uses either a /dev/tty serial port or a file as input. As long as you can make the RSP1A output the navtex messages in ascii, it shouldn't be hard to make it work together.

**Comment by isarychkin** [comment]
<It currently uses either a /dev/tty serial port or a file as input>
Hi there.  So how "file as input" can be configured in plugin UI?
Cheers
Igor
