### ISSUE TITLE
Messages received but browse window stays black

### ISSUE THREAD

**Issue by pa1pdr** [htool/signalk-navtex-plugin#2]
A number of messages have been stored by the plugin in Signalk paths e.g. resources.navtex.I.E.69. The browser window remains empty (black, no buttons or anything)) on IE, Safari, iPad. The SK server runs on Windows 10.

**Comment by htool** [comment]
Any info in the console.log?

**Comment by pa1pdr** [comment]
With the debugginng enabled:
Jun 26 10:37:26 2023-06-26T08:37:26.289Z signalk-navtex-plugin [{"station":"ALL","messageTypes":{"0":true}}]
Jun 26 10:37:26 GET /plugins/signalk-navtex-plugin/stations 304 3.334 ms - -
**Jun 26 10:37:29 GET /plugins/signalk-navtex-plugin/stations 401 4.882 ms - 91**
Jun 26 10:37:52 2023-06-26T08:37:52.431Z signalk-navtex-plugin [{"station":"ALL","messageTypes":{"0":true}}]
Jun 26 10:37:52 GET /plugins/signalk-navtex-plugin/stations 304 2.171 ms - -
Jun 26 10:37:59 GET /admin/ 200 2.073 ms - 562
Jun 26 10:37:59 GET /skServer/loginStatus 200 2.254 ms - 204
Jun 26 10:38:00 GET /@signalk/freeboard-sk/assets/icons/icon-72x72.png 304 6.766 ms - -
Jun 26 10:38:00 GET /@signalk/instrumentpanel/icons/instrumentpanel-72x72.png 304 4.835 ms - -
Jun 26 10:38:00 GET /signalk-navtex-plugin/signalk-logo.png 304 9.335 ms - -
Jun 26 10:38:00 GET /vhfinfo/signalk-logo.png 304 8.670 ms - -

Is this what you are looking for?

**Comment by htool** [comment]
No, browser side, the chrome dev console.

**Comment by pa1pdr** [comment]
This is after a browser refresh
Jun 26 10:42:19 GET /jquery/dist/jquery.min.js 304 1.108 ms - -
Jun 26 10:42:19 GET /signalk-navtex-plugin/date.format.js 304 3.996 ms - -
Jun 26 10:42:19 GET /signalk-navtex-plugin/Consolas.woff 304 1.995 ms - -
Jun 26 10:42:19 GET /plugins/signalk-navtex-plugin/stations 401 1.021 ms - 91

**Comment by pa1pdr** [comment]
Sorry, had to install chrome first:
Skipping welcome message: {"name":"signalk-server","version":"1.46.3","self":"vessels.urn:mrn:imo:mmsi:244810655","roles":["master","main"],"timestamp":"2023-06-26T09:27:03.885Z"}
:3000/plugins/signalk-navtex-plugin/stations:1     Failed to load resource: the server responded with a status of 401 (Unauthorized)
(index):77 Blur

**Comment by htool** [comment]
This looks like an authentication issue. I'm not running it as https, so didn't run into this.
So noted, but not likely to be fixed by me any time soon.

**Comment by pa1pdr** [comment]
Not sure if it is HTTPS related. If I click the URL localhost:3000/plugins/signalk-navtex-plugin/stations it asks me to authenticate (as admin). When I do it spits out:
["undefined.*"]

**Comment by pa1pdr** [comment]
Pity it is not fixed soon :-(

**Comment by pa1pdr** [comment]
When I configure a particular station in the plugin config (instead of All), it works!

**Comment by pa1pdr** [comment]
As a feature suggestion: it would be nice if the browser UI had selectors for station and message type too.
And it would be great if messages included an indication of the source station too
