### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by moserwi** [htool/signalk-navtex-plugin#4]
Sorry I am fairly new to SignalK Server. My Serial Port ist /dev/ttyUSB0 with a NASA-Navtex-USB connected. The connection is tested with a test script and the demo message is correctly received. The Port is defined in the signalk-navtex-plugin  options.

Well I wonder why thew signalk-navtex-plugin  is shown in the webapps section but there is no application but only a blank screen.

Thank you - willi

**Comment by moserwi** [comment]
btw.. install was doen with npm

**Comment by htool** [comment]
If the screen is blank, there are no messages.

**Comment by Haimana** [comment]
Hello, 
NASA PC Navtex USB here, RPi3+ and OP3 here. 
Navtex connected on /dev/ttyUSB2, 38400bps and not managed by OP3.
Still having black screen app even some messages are already stored inside PC Navtex.

I tested the connection with gtkterm and I can get stored messages with $S command.

This plugin should display also the perviously stored messages? 

I cannot say something about new incoming messages, the Navtex is on the bench and no antenna

Thanks, 
SeB
