### ISSUE TITLE
Encouragement to fix this plugin?

### ISSUE THREAD

**Issue by BramdVries** [htool/signalk-navtex-plugin#5]
hi Hans, 
I'd love to use this with SK 2.x. Would a nice bottle of wine or a few bottles of specialty beers be enough encouragement to fix the serial issue mentioned in the other issue?
Thanks,
Bram

**Comment by htool** [comment]
Hi Bram,
I'm busy with some personal life things and haven't moved to 2.x yet.
Once I do, which I expect will happen over the coming months, I'll run into the issues and fix them.

**Comment by BramdVries** [comment]
wow, that was quick! 😀
I understand other things can be more important and appreciate it has your attention nonetheless. I will be patient 😀

**Comment by pa1pdr** [comment]
Same here..

**Comment by htool** [comment]
Should be fixed now. Upgraded Serialport and although I'm not running SignalK v2 yes, the plugin is working ok here.

**Comment by BramdVries** [comment]
Great, thanks! Will test soon.
